export type {
  ServerToClientEvents,
  ClientToServerEvents,
  ScoreUpdate,
  DmdDisplay,
  CinematicClip,
  GameStart,
  GameOver,
  GameStats,
  LeaderboardEntry,
  GlobalStats,
  ButtonId,
  ButtonAction,
  ButtonInput,
  TiltInput,
  SensorInput,
} from './socket-events'
