export type {
  ServerToClientEvents,
  ClientToServerEvents,
  ScoreUpdate,
  DmdDisplay,
  DmdAtmosphere,
  GameStart,
  GameOver,
  LeaderboardEntry,
  ButtonId,
  ButtonAction,
  ButtonInput,
  TiltInput,
  SensorInput,
} from './socket-events'
