export const SWING_RAD = 0.65;
export const SWING_SMOOTH = 0.42;
export const FLIPPER_SWING_AXIS: 'x' | 'y' | 'z' = 'x';
export const HINGE_INSET_FROM_EDGE = 0.18;
export const FLIPPER_POWER = 0.138;
export const FLIPPER_RESTITUTION = 0.22;
export const FLIPPER_FRICTION = 0.05;
export const FLIPPER_TRIGGER = 0.15;
export const FLIPPER_Z_MIN = 0.20;
export const FLIPPER_Z_MAX = 0.33;
export const FLIPPER_LEFT_X_MIN = -0.085;
export const FLIPPER_LEFT_X_MAX = 0.015;
export const FLIPPER_LEFT_MID_X = -0.035;
export const FLIPPER_RIGHT_X_MIN = -0.015;
export const FLIPPER_RIGHT_X_MAX = 0.055;
export const FLIPPER_RIGHT_MID_X = 0.020;
export const INITIAL_LIVES = 3;
export const PLUNGER_CHARGE_MS = 1800;
// Min relevé : à pleine masse, 0.22*0.6/0.08 ≈ 1.65 m/s, assez pour franchir
// la courbe de sortie. Max = tir complet (~2.75 m/s).
export const PLUNGER_MIN_FACTOR = 0.6;
export const PLUNGER_MAX_FACTOR = 1.0;
