export {
  DEMOGORGON_REVEAL_SCORE,
  SCORE_DEMOGORGON_REVEAL,
  SCORE_DEMOGORGON_TARGET,
  VECNA_REVEAL_SCORE,
  SCORE_VECNA_REVEAL,
  SCORE_VECNA_TARGET,
} from './BossRegistry';

export const SCORE_BUMPER = 100;
export const SCORE_BUMP   = 30;
export const SCORE_SLINGSHOT = 10;
export const SCORE_POP_ZONE = 50;
export const SCORE_RAMP = 200;
export const SCORE_DROP_TARGET = 75;
export const SCORE_DROP_COMPLETE = 500;
