export const UPSIDE_DOWN_TRANSITION_DURATION = 4;
export const UPSIDE_DOWN_TRANSITION_BLACKOUT = 0.12;
export const UPSIDE_DOWN_TRANSITION_REVEAL = 0.55;
export const UPSIDE_DOWN_TRANSITION_RESTORE = 0.35;
export const UPSIDE_DOWN_TRANSITION_TREMOR = 2.2;
export const UPSIDE_DOWN_TRANSITION_STROBE_HZ = 11;
export const UPSIDE_DOWN_TRANSITION_HOLD =
  UPSIDE_DOWN_TRANSITION_DURATION
  - UPSIDE_DOWN_TRANSITION_BLACKOUT
  - UPSIDE_DOWN_TRANSITION_REVEAL
  - UPSIDE_DOWN_TRANSITION_RESTORE;

export const UPSIDE_DOWN_PLAYFIELD_SHADE_W = 0.58;
export const UPSIDE_DOWN_PLAYFIELD_SHADE_D = 1.02;
export const UPSIDE_DOWN_PLAYFIELD_TILT = Math.atan2(0.110, 0.970);
export const UPSIDE_DOWN_PLAYFIELD_SHADE_Y = 1.062;
export const UPSIDE_DOWN_PLAYFIELD_SHADE_Z = -0.067;

export const UPSIDE_DOWN_PORTAL_OPEN_POLISH = 0.2;
export const UPSIDE_DOWN_PORTAL_PULSE_SPEED = 2.4;
export const UPSIDE_DOWN_PORTAL_ACCENT_PULSE_SPEED = 1.6;
export const UPSIDE_DOWN_PORTAL_VINE_COUNT = 5;

export const UPSIDE_DOWN_ATMOSPHERE_BLEND = 2.8;
export const UPSIDE_DOWN_ATMOSPHERE_BG = 0x0a0818;
export const UPSIDE_DOWN_ATMOSPHERE_TINT = 0x2a1835;
export const UPSIDE_DOWN_ATMOSPHERE_SURFACE_TINT = 0x1a1220;
export const UPSIDE_DOWN_ATMOSPHERE_WALL_TINT = 0x1a2048;
export const UPSIDE_DOWN_ATMOSPHERE_DECOR_TINT = 0x3a1848;
export const UPSIDE_DOWN_ATMOSPHERE_EMISSIVE = 0x551133;
export const UPSIDE_DOWN_ATMOSPHERE_DECOR_EMISSIVE = 0x772244;
export const UPSIDE_DOWN_ATMOSPHERE_EXPOSURE = 1.05;
export const UPSIDE_DOWN_ATMOSPHERE_AMBIENT_INTENSITY = 0.52;
export const UPSIDE_DOWN_ATMOSPHERE_HEMI_INTENSITY = 0.32;
export const UPSIDE_DOWN_ATMOSPHERE_DIR_INTENSITY = 1.05;
export const UPSIDE_DOWN_ATMOSPHERE_FILL_INTENSITY = 0.38;
export const UPSIDE_DOWN_ATMOSPHERE_SHADE_OPACITY = 0.46;
export const UPSIDE_DOWN_ATMOSPHERE_SHADE_COLOR = 0x180818;
export const UPSIDE_DOWN_ATMOSPHERE_FOG_COLOR = 0x1a0a20;
export const UPSIDE_DOWN_ATMOSPHERE_FOG_DENSITY = 0.19;
export const UPSIDE_DOWN_ATMOSPHERE_PULSE_EXPOSURE_MIN = 0.95;
export const UPSIDE_DOWN_ATMOSPHERE_PULSE_EXPOSURE_MAX = 1.08;
export const UPSIDE_DOWN_ATMOSPHERE_PULSE_EXPOSURE_SPEED = 1.8;
export const UPSIDE_DOWN_ATMOSPHERE_STROBE_HZ = 4;
export const UPSIDE_DOWN_ATMOSPHERE_BLEND_STROBE_HZ = 11;
export const UPSIDE_DOWN_ATMOSPHERE_SPORE_COUNT = 28;

export const UPSIDE_DOWN_HINT_MS = 4200;
