services:
  db:
    image: postgres:15-alpine
    container_name: pinball-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pinball
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: pinball-server
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/pinball?schema=public"
    ports:
      - "3334:3001"
    depends_on:
      - db

  playfield:
    build:
      context: .
      dockerfile: apps/playfield/Dockerfile
    container_name: pinball-playfield
    ports:
      - "3333:3000"
    depends_on:
      - server

  scoreboard:
    build:
      context: .
      dockerfile: apps/dmd/Dockerfile
    container_name: pinball-scoreboard
    ports:
      - "3335:3000"
    depends_on:
      - server

  leaderboard:
    build:
      context: .
      dockerfile: apps/backglass/Dockerfile
    container_name: pinball-leaderboard
    ports:
      - "3336:3000"
    depends_on:
      - server

volumes:
  postgres_data:
