import { mapAsset } from '../manifest';

/** Cinématique entrée Upside Down (premier passage portail). */
export const PORTAL_ENTER_TEXTURE_URL = mapAsset('playfield/upsidedown.jpg');
/** Cinématique retour après victoire Vecna (passage balle dans le trou). */
export const RETURN_PORTAL_TEXTURE_URL = mapAsset('playfield/fin_combat_vecna.png');

export const UPSIDE_DOWN_TRANSITION_DURATION = 4;
export const UPSIDE_DOWN_TRANSITION_BLACKOUT = 0.12;
export const UPSIDE_DOWN_TRANSITION_REVEAL = 0.55;
export const UPSIDE_DOWN_TRANSITION_RESTORE = 0.35;
export const UPSIDE_DOWN_TRANSITION_TREMOR = 2.2;
export const UPSIDE_DOWN_TRANSITION_STROBE_HZ = 11;
export const UPSIDE_DOWN_TRANSITION_HOLD =
  UPSIDE_DOWN_TRANSITION_DURATION
  - UPSIDE_DOWN_TRANSITION_BLACKOUT
  - UPSIDE_DOWN_TRANSITION_REVEAL
  - UPSIDE_DOWN_TRANSITION_RESTORE;

export const UPSIDE_DOWN_PORTAL_REVEAL_DELAY = 3;
export const UPSIDE_DOWN_PORTAL_OPEN_DURATION = 2.5;
export const UPSIDE_DOWN_PORTAL_OPEN_POLISH = 0.2;
export const UPSIDE_DOWN_PORTAL_ANCHOR_NAMES = [
  'portal_upsidedown',
  'vis_demogorgon_portal_demog_portal_ref_skeleton',
  'demogorgon_portal_demog_portal_ref_skeleton',
] as const;
export const UPSIDE_DOWN_PORTAL_PULSE_SPEED = 2.4;
export const UPSIDE_DOWN_PORTAL_ACCENT_PULSE_SPEED = 1.6;
export const UPSIDE_DOWN_PORTAL_VINE_COUNT = 5;

export const UPSIDE_DOWN_ATMOSPHERE_BLEND = 2.8;
export const UPSIDE_DOWN_ATMOSPHERE_BG = 0x0a0818;
export const UPSIDE_DOWN_ATMOSPHERE_TINT = 0x2a1835;
export const UPSIDE_DOWN_ATMOSPHERE_SURFACE_TINT = 0x1a1220;
export const UPSIDE_DOWN_ATMOSPHERE_WALL_TINT = 0x1a2048;
export const UPSIDE_DOWN_ATMOSPHERE_DECOR_TINT = 0x3a1848;
export const UPSIDE_DOWN_ATMOSPHERE_EMISSIVE = 0x551133;
export const UPSIDE_DOWN_ATMOSPHERE_DECOR_EMISSIVE = 0x772244;
export const UPSIDE_DOWN_ATMOSPHERE_EXPOSURE = 1.22;
export const UPSIDE_DOWN_ATMOSPHERE_AMBIENT_INTENSITY = 0.68;
export const UPSIDE_DOWN_ATMOSPHERE_HEMI_INTENSITY = 0.45;
export const UPSIDE_DOWN_ATMOSPHERE_DIR_INTENSITY = 1.22;
export const UPSIDE_DOWN_ATMOSPHERE_FILL_INTENSITY = 0.52;
export const UPSIDE_DOWN_ATMOSPHERE_SHADE_OPACITY = 0.28;
export const UPSIDE_DOWN_ATMOSPHERE_SHADE_COLOR = 0x180818;
export const UPSIDE_DOWN_ATMOSPHERE_FOG_COLOR = 0x1a0a20;
export const UPSIDE_DOWN_ATMOSPHERE_FOG_DENSITY = 0.11;
export const UPSIDE_DOWN_ATMOSPHERE_PULSE_EXPOSURE_MIN = 1.1;
export const UPSIDE_DOWN_ATMOSPHERE_PULSE_EXPOSURE_MAX = 1.26;
export const UPSIDE_DOWN_ATMOSPHERE_PULSE_EXPOSURE_SPEED = 1.8;
export const UPSIDE_DOWN_ATMOSPHERE_STROBE_HZ = 4;
export const UPSIDE_DOWN_ATMOSPHERE_BLEND_STROBE_HZ = 11;
export const UPSIDE_DOWN_ATMOSPHERE_SPORE_COUNT = 28;

export const UPSIDE_DOWN_HINT_MS = 4200;
